# NumPy Tutorial for Beginners

## Introduction
NumPy (Numerical Python) is a Python library used for numerical computations and working with arrays. It provides a high-performance multidimensional array object, and tools for working with these arrays.

## Installation
You can install NumPy using pip:
```python
pip install numpy

## Importing Numpy
To use NumPy in your code, you need to import it first by:

In [1]:
import numpy as np

### Creating Arrays
You can create a Numpy array using the `np.array()` function:

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


### Array Operation
Numpy arrays support all standard arithmetic operations:

In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
print(arr1 + arr2)

# Subtraction
print(arr1 - arr2)

# Multiplication
print(arr1 * arr2)

# Division
print(arr1 / arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


### Indexing
You can access elements of a Numpy array using indices:

In [4]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])  # prints 1
print(arr[2])  # prints 3

1
3


### Slicing
You can slice Numpy arrays similar to Python lists:

In [5]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])  # prints [2 3 4]

[2 3 4]


### Shape and Reshape
You can get the shape of an array using the `shape` attribute and change the shape using `reshape` function:

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # prints (2, 3)

reshaped_arr = arr.reshape(3, 2)
print(reshaped_arr)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
